### ISSUE TITLE
notly() return NULL

### ISSUE THREAD

**Issue by zhipengliux** [gdmcdonald/notly#3]
Dear author:
     when i use notly() convert plotly to ggplot, return NULL
<img width="184" alt="image" src="https://user-images.githubusercontent.com/71112013/202968456-dd7f680e-10ba-49a3-a664-d13901bf2dcb.png">

**Comment by gdmcdonald** [comment]
Hi there! Thanks for using notly.

Can you please provide more information or a [reproducible example](https://gist.github.com/hadley/270442)?

For example, was the plotly plot created using `notly::ggplotly()` ? This is required for it to work. if it was created with `plotly::ggplotly()` then it won't work unfortunately.

**Comment by zhipengliux** [comment]
Thanks
this is my data :pc.mat
PC1	PC2	PC3	tissue	br	ind
-362.8498992	-44.82757938	11.28753196	GW	JJ	JJ23GW
-369.9046352	-39.26382701	10.98134288	GW	JJ	JJ25GW
-368.061813	-32.22282423	18.46833169	GW	JJ	JJ29GW
-345.394035	-10.27203652	23.58357576	GW	DN	DN1GW
-214.9940423	-73.31390408	-10.80878716	GW	DN	DN3GW
-347.9061853	-51.22769365	6.210756368	GW	DN	DN7GW
82.55275001	-104.5670507	-159.9541784	FG	JJ	JJ23FG
51.78889145	-68.22909508	-160.4890432	FG	JJ	JJ25FG
80.79561694	3.740722599	-123.3187984	FG	JJ	JJ29FG
65.17676478	58.22885831	-88.68677045	FG	DN	DN1FG
88.31974633	-104.2202715	-149.5237905	FG	DN	DN3FG
76.25182438	-83.81720839	-160.5504758	FG	DN	DN7FG
92.40477316	107.5274865	-15.26151502	JNX	JJ	JJ23JNX
99.89890337	30.91850314	-45.25192337	JNX	JJ	JJ25JNX
95.24263963	88.80282593	-24.76337202	JNX	JJ	JJ29JNX
83.14119521	149.843813	6.725916353	JNX	DN	DN1JNX
93.24898149	88.98055764	-23.71052128	JNX	DN	DN3JNX
88.57356686	109.6072665	-8.277994816	JNX	DN	DN7JNX
97.87698138	-5.560337678	84.06373106	QLX	JJ	JJ23QLX
96.87756869	53.13227168	5.788945538	QLX	JJ	JJ25QLX
101.3366299	40.51400677	108.401352	QLX	JJ	JJ29QLX
98.19337727	-63.40914898	45.63791645	QLX	DN	DN1QLX
95.47127543	-29.15557616	62.2404779	QLX	DN	DN3QLX
99.65597617	-53.71097871	49.89235553	QLX	DN	DN7QLX
101.2851331	-15.28133517	108.253902	NDQX	JJ	JJ23NDQX
103.9747324	-76.48008038	86.90079431	NDQX	JJ	JJ25NDQX
106.2604922	-78.65803575	86.92261763	NDQX	JJ	JJ29NDQX
99.84007486	-75.8112804	100.1424981	NDQX	DN	DN1NDQX
92.67767961	-5.685653602	113.0114955	NDQX	DN	DN3NDQX
98.40310761	-90.54965225	68.29752941	NDQX	DN	DN7NDQX

this is my code
`plot_ly(x= ~PC1,y= ~PC2,z= ~PC3,color = ~tissue,symbol = ~br,symbols = symbols) %>% 
  add_trace(data = pc.mat, type = "scatter3d", mode = 'markers') -> plotly
notly(plotly)
`
I used plotly::save_image(plotly,"pca3d.pdf"), but the saved pdf only legend is vector, main part is not vector, so that, we want to convert plotly to ggplot, then use ggsave()

**Comment by zhipengliux** [comment]
Thanks for your reply
  Aha! It doesn't work! is there any way to convert ployly to ggplot! 
Thanks again

**Comment by gdmcdonald** [comment]
Yep, `notly` can't do that unfortunately.  But you could try using a different package, e.g. Using [gg3D](http://htmlpreview.github.io/?https://github.com/AckerDWM/gg3D/blob/master/gg3D-vignette.html )


```
df<-data.frame(
  PC1 = c(-362.8498992, -369.9046352, -368.061813, -345.394035, -214.9940423, -347.9061853, 82.55275001, 51.78889145, 
          80.79561694, 65.17676478, 88.31974633, 76.25182438, 92.40477316, 
          99.89890337, 95.24263963, 83.14119521, 93.24898149, 88.57356686, 
          97.87698138, 96.87756869, 101.3366299, 98.19337727, 95.47127543, 
          99.65597617, 101.2851331, 103.9747324, 106.2604922, 99.84007486, 
          92.67767961, 98.40310761), 
  PC2 = c(-44.82757938, -39.26382701, -32.22282423, -10.27203652, -73.31390408, -51.22769365, -104.5670507, 
          -68.22909508, 3.740722599, 58.22885831, -104.2202715, -83.81720839, 
          107.5274865, 30.91850314, 88.80282593, 149.843813, 88.98055764, 
          109.6072665, -5.560337678, 53.13227168, 40.51400677, -63.40914898, 
          -29.15557616, -53.71097871, -15.28133517, -76.48008038, -78.65803575, 
          -75.8112804, -5.685653602, -90.54965225), 
  PC3 = c(11.28753196, 10.98134288, 18.46833169, 23.58357576, -10.80878716, 6.210756368, 
          -159.9541784, -160.4890432, -123.3187984, -88.68677045, -149.5237905, 
          -160.5504758, -15.26151502, -45.25192337, -24.76337202, 6.725916353, 
          -23.71052128, -8.277994816, 84.06373106, 5.788945538, 108.401352, 
          45.63791645, 62.2404779, 49.89235553, 108.253902, 86.90079431, 
          86.92261763, 100.1424981, 113.0114955, 68.29752941), 
  tissue = c("GW", "GW", "GW", "GW", "GW", "GW", "FG", "FG", "FG", "FG", "FG", "FG", 
             "JNX", "JNX", "JNX", "JNX", "JNX", "JNX", "QLX", "QLX", "QLX", 
             "QLX", "QLX", "QLX", "NDQX", "NDQX", "NDQX", "NDQX", "NDQX", "NDQX"), 
  br = c("JJ", "JJ", "JJ", "DN", "DN", "DN", "JJ", "JJ", 
         "JJ", "DN", "DN", "DN", "JJ", "JJ", "JJ", "DN", "DN", "DN", "JJ", 
         "JJ", "JJ", "DN", "DN", "DN", "JJ", "JJ", "JJ", "DN", "DN", "DN"), 
  ind = c("JJ23GW", "JJ25GW", "JJ29GW", "DN1GW", "DN3GW", "DN7GW", 
          "JJ23FG", "JJ25FG", "JJ29FG", "DN1FG", "DN3FG", "DN7FG", "JJ23JNX", 
          "JJ25JNX", "JJ29JNX", "DN1JNX", "DN3JNX", "DN7JNX", "JJ23QLX", 
          "JJ25QLX", "JJ29QLX", "DN1QLX", "DN3QLX", "DN7QLX", "JJ23NDQX", 
          "JJ25NDQX", "JJ29NDQX", "DN1NDQX", "DN3NDQX", "DN7NDQX")
)

devtools::install_github("AckerDWM/gg3D")
library(gg3D)

th = 130
ph = 45

ggplot(df, aes(x=PC1, y=PC2, z=PC3, color=tissue, shape = br)) + 
  theme_void() +
  axes_3D(theta=th, phi = ph) +
  labs_3D(theta=th, phi = ph,
          labs=c("PC1", "PC2", "PC3"),
          hjust=c(0, 1, 1), 
          vjust=c(1, 1, -0.2), 
          angle=c(0, 0, 90)) +  
  stat_3D(theta=th, phi = ph)
```

**Comment by zhipengliux** [comment]
Thanks a million. I am all gratitude.
